### ISSUE TITLE
Small visual improvements

### ISSUE THREAD

**Issue by benmann** [bower/bower.github.io#189]
Before opening a PR or something I thought I'd just create an issue to adress what I think we should have a look at.
- Header should be unified over all pages/sub-ages
- Do we want a banner, to draw attention / get more contributors / other cases?
- Related: should we have "improve / fork me on GitHub" ribbon in the corner (search & stats do)?
- Media queries... /css partly looks like the wild west with queries at 680px and 667px in different files, partly overwriting styles. I'd like to clear that up and maybe even get rid of `medias.css` altogether.
- `.network-nav` just disappears on smaller sizes --> can't access blog anymore. We should find a solution to keep that menu visible.
- Menu on the left could look better in queries (any ideas?) odd/even coloring is a good idea, but also draws more attention to the dark ones, which seems confusing (to me!)

Also the sub-pages (stats & search) use less instead of CSS. I'm fine with it but wouldn't mind rewriting to unify it over the entire front-end. Because talk is cheap I made a slightly(!) changed header with a banner and attached screenshots. It's not really done, but if people agree I'd be happy to finalize in that direction. /cc: @desandro 

![screenshot](https://cloud.githubusercontent.com/assets/7561396/11457457/37feda8a-96aa-11e5-991e-23d96efb6ca0.jpg)

**Comment by desandro** [comment]
Thanks for taking a shot at this!

> Header should be unified over all pages/sub-ages

Can you clarify what is not unified? I don't feel that the screenshots are a better design than what's already implemented. The homepage header doesn't need to be improved. I'm interested what solution you have for sub-pages.

> Do we want a banner, to draw attention / get more contributors / other cases?

Having a banner on the homepage is sufficient. Having it on every page feels a bit desparate IMO.

> Related: should we have "improve / fork me on GitHub" ribbon in the corner (search & stats do)?

I say no. We have the "Help improve these docs" link in the bottom for the docs, and "Bower on GitHub" in the sidebar. If anything, it might be a good idea to add a GitHub star button in the side bar, instead of the generic link.

> Media queries... /css partly looks like the wild west with queries at 680px and 667px in different files, partly overwriting styles. I'd like to clear that up and maybe even get rid of medias.css altogether.

Yeah, the CSS has had multiple authors with multiple methodologies. Definitely in need of standardization. Before making any changes, I would focus on this clean up effort.

> .network-nav just disappears on smaller sizes --> can't access blog anymore. We should find a solution to keep that menu visible.

Okay, but I'd say only for the homepage. The network nav is not as useful if you're visiting sub pages

>  Menu on the left could look better in queries (any ideas?) odd/even coloring is a good idea, but also draws more attention to the dark ones, which seems confusing (to me!)

Mobile menu is awful. Totally needs to be redesigned. Even using the simplified list would be better than the big blocks.

> Also the sub-pages (stats & search) use less instead of CSS. I'm fine with it but wouldn't mind rewriting to unify it over the entire front-end.

Yes. I'd include this in the refactor effort. Personally, I like vanilla CSS as its easier to debug and requires one less build step.

**Comment by BenMann** [comment]
Thanks for the quick reply.
So there are a few points we can already agree on:
* Clean up CSS (that includes rewriting LESS to CSS in stats/search)
* Add removable banner on home only (is 80% of orignal red ok? Stick with original red?)
* Get rid of ribbons
* Rework mobile menu

What I meant with unifying the headers is directly related to the sub-pages and the network-nav. Right now on blog, search and stats the logo has literally three different sizes and so does the header in height. I would like to make them all look like the header on the blog page.  

Related to this, I'd like to pick up this one again:
> .network-nav just disappears on smaller sizes --> can't access blog anymore. We should find a > solution to keep that menu visible.
>> Okay, but I'd say only for the homepage. The network nav is not as useful if you're visiting sub pages

I understand it is not remotely as important as the menu on the left, which allows you to navigate the docs, but imagine a user coming to the latest blog post on a phone. Maybe she saw it on twitter and clicked the link. In that situation you are literally stuck and can't move around the site at all, becuse the nav and the logo both disappear on all (sub-) pages. That means you can't really find out more about Bower, if you don't know it yet (unless you manually change the URL, which is a bit laborious).  
That's also really the only reason I touched the header. The rest was just alignment and that brought about a need to make the logo slightly smaller (screenshot attached). In smaller queries the nav then aligns with the `h1` and content (as seen above). That however are points I consider peronal preference and I'm more than okay to go with your choice visually. 

<img width="968" alt="alignment" src="https://cloud.githubusercontent.com/assets/7561396/11464838/c58f9b62-9733-11e5-8e07-e938f43a91cb.png">

**Comment by desandro** [comment]
> that includes rewriting LESS to CSS in stats/search

Ah, sorry. My concern that LESS and vanilla CSS were being used simultaneously on this repo. Using LESS on other projects isn't a big concern.

> What I meant with unifying the headers is directly related to the sub-pages and the network-nav. Right now on blog, search and stats the logo has literally three different sizes and so does the header in height. I would like to make them all look like the header on the blog page.

Ah, okay! :+1: Having a consistent header on all bower sites (bower.io, stats, & search) would be great! One of those things I've been meaning to do, but never got around to.

> Add removable banner on home only (is 80% of orignal red ok? Stick with original red?)

Stick with [brand red](http://bower.io/docs/about/#colors)

> Get rid of ribbons

Okay. In their stead, let's have consistent treatment for "improve this site." Whether that be in the footer or somewhere else.

> In that situation you are literally stuck and can't move around the site at all, becuse the nav and the logo both disappear on all (sub-) pages. 

Good point!

> The rest was just alignment and that brought about a need to make the logo slightly smaller (screenshot attached).

Fair point. The misalignment on the home page is intentional. The big logo allows for bigger text. This felt more like a landing page. I'm okay with the misalignment here for this reason.

**Comment by BenMann** [comment]
So that's the latest:
* Clean up CSS
* Add removable banner on home only (brand red)
* Get rid of ribbons, add link in footer or side nav ("improve this site")
* Rework mobile menu
* Consistent header on all bower sites (bower.io, stats, search)   
=> Try to keep menu, so you can navigate at all times/sizes
* Homepage header stays untouched no matter what
   
   
> One of those things I've been meaning to do, but never got around to.

Any more of those, let me know. 😉

I'll start a fork and PRs as soon as I have a few minutes of time. Would we awesome if you reviewed them before merge — just in case. I'll reference this issue and keep it open until it's all done.

**Comment by prometheansacrifice** [comment]
@BenMann :+1: 
Turned your list items into check boxes :)

**Comment by cedced19** [comment]
I changed ribbon here: https://github.com/bower/search/pull/82

**Comment by pertrai1** [comment]
@BenMann :+1: Looks great

**Comment by pertrai1** [comment]
@BenMann do the final 2 checkboxes still need to be done or should be close this?

**Comment by BenMann** [comment]
@pertrai1 The second one should definetely be done! First one, I don't know. I'd go with yes, cause it won't hurt to get some more people on board. I also started the second for search, then got carried away with other fixes on search. I hope to get this whole issue done by the end of the year. Join in with contributions if you want to :wink:

**Comment by pertrai1** [comment]
@BenMann - cool I will definitely join in with contributions. Will take a look tonight to see where you are at.
