### ISSUE TITLE
Missing/Odd Search Results - Hammer

### ISSUE THREAD

**Issue by mscarchilli** [bower/bower.github.io#251]
If you search for "hammer", it excludes all results for "hammerjs". You need to literally search for "hammerj" at a minimum, or the full "hammerjs" to find the correct package. Considering how many stars hammerjs has over any results for just hammer, one would think that is the package more people are looking for. 

Perhaps loading more results or paginating results, or put letters over "-" for the search query?

I also noticed that there was two results for hammerjs, with different owner names, but both go to the same git repo.

**Comment by julmot** [comment]
@mscarchilli Search results will be fetched from the libraries.io API, e.g. using:
https://libraries.io/api/search?platforms=bower&q=hammerjs
Therefore this is not related to the Bower website, but to this API. 

However, I can understand your situation. And I furthermore think that most users expect to find "hammer.js" when searching for "hammer". However, all the packages that will be listed for "hammer" contain a single word "hammer" in either the keywords, the title or the description. The actual package "hammer.js" doesn't, so I suppose that this is why the others are listed before. I think this behavior could be fixed by adding a keyword "hammer" to the "keywords" array in bower.json.

![hammer](https://cloud.githubusercontent.com/assets/8310677/16184630/2261cf48-36be-11e6-934e-ff05f04f5d86.png)
